services:

  coopmaster_camera_driver:
    image: jardathedev/coopmaster-camera-driver:latest
    restart: always
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - CHICKEN_CAMERA_IP=192.168.1.64
      - CHICKEN_CAMERA_USERNAME=admin
      - CHICKEN_CAMERA_PASSWORD=Heslo123456*
      - DOG_CAMERA_IP=192.168.1.64
      - DOG_CAMERA_USERNAME=admin
      - DOG_CAMERA_PASSWORD=Heslo123456*
    networks:
      - coopmaster

  coopmaster_scale_driver:
    image: jardathedev/coopmaster-scale-driver:latest
    restart: always
    devices:
      # Map the USB device from the host to the container
      # Example for a common USB serial device
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "9004:9004"
    environment:
      - HOST=localhost
      - PORT=9004
      - WEIGHT_COM_PORT=/dev/ttyUSB0
      - WEIGHT_INTERVAL_SEC=2
    networks:
      - coopmaster

#  coopmaster_door_driver:
#    image: jardathedev/coopmaster-door-driver:latest
#    restart: always
#    ports:
#      - "9005:9005"

  coopmaster_nest_watcher:
    image: jardathedev/coopmaster-nest-watcher:latest
    restart: always
    ports:
      - 9007:9007
    env_file:
      - .env
    environment:
      - HOST=localhost
      - PORT=9007
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=/nest_watcher/count
    networks:
      - coopmaster

  coopmaster_dog_alarm:
    image: jardathedev/coopmaster-dog-alarm:latest
    restart: always
    ports:
      - 9008:9008
    env_file:
      - .env
    environment:
      - HOST=localhost
      - PORT=9008
      - DOG_CAMERA_PORT=9001
      - DOG_CAMERA_HOST=localhost
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=dog/detected
    networks:
      - coopmaster

#  coopmaster_door_assistant:
#    image: jardathedev/coopmaster-door-assistant:latest
#    restart: always
#    ports:
#      - "9006:9006"
#
  coopmaster_chicken_watch_guard:
    image: jardathedev/coopmaster-chicken-watch-guard:latest
    restart: always
    ports:
      - 9003:9003
    env_file:
      - .env
    environment:
      - HOST=localhost
      - PORT=9003
      - CHICKEN_CAMERA_PORT=9001
      - CHICKEN_CAMERA_HOST=localhost
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_TOPIC=chicken/count
    networks:
      - coopmaster


  coop-solution-db:
    image: postgres:15
    container_name:  coop-solution-db
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pg_isready -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s
    restart: always
    env_file:
      - .env
    environment:
      - DB_POSTGRES_EXTRA_CONFIG=shared_preload_libraries=pg_stat_statements
    ports:
      - "${DB_PORT}:5432" # Port for remote accessing the database
    networks:
      - coopmaster
    volumes:
      - ./postgres_backup:/storage/backup
      - ./postgres_data:/storage/data


  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - coopmaster

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - './home_assistant/config:/config'
    environment:
      - TZ=Europe/Bratislava # get your Time Zone from - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8123:8123'
    restart: always
    networks:
      - coopmaster


networks:
  coopmaster:
    name: coopmaster