services:

  coopmaster_camera_driver:
    image: jardathedev/coopmaster-camera-driver:latest
    restart: always
    pull_policy: always
    container_name: coopmaster_camera_driver
    ports:
      - 9001:9001
    environment:
      - PORT=9001
      - CHICKEN_CAMERA_IP=${CHICKEN_CAMERA_IP}
      - CHICKEN_CAMERA_USERNAME=admin
      - CHICKEN_CAMERA_PASSWORD=Wula9321*
      - DOG_CAMERA_IP=%{DOG_CAMERA_IP}
      - DOG_CAMERA_USERNAME=admin
      - DOG_CAMERA_PASSWORD=Wula9321*
    networks:
      - coopmaster

  coopmaster_scale_driver:
    image: jardathedev/coopmaster-scale-driver:latest
    restart: always
    pull_policy: always
    container_name: coopmaster_scale_driver
    devices:
      # Map the USB device from the host to the container
      # Example for a common USB serial device
      - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/ttyUSB1:/dev/ttyUSB1
      # - /dev/ttyUSB2:/dev/ttyUSB2
    ports:
      - 9004:9004
    environment:
      - HOST=localhost
      - PORT=9004
      - WEIGHT_COM_PORT=/dev/ttyUSB0
      - WEIGHT_INTERVAL_SEC=2
    networks:
      - coopmaster

  coopmaster_room_driver:
    image: jardathedev/coopmaster-room-driver:latest
    container_name: coopmaster_room_driver
    restart: always
    pull_policy: always
    devices:
      # Map the USB device from the host to the container
      # Example for a common USB serial device
      # - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      # - /dev/ttyUSB2:/dev/ttyUSB2
    ports:
      - 9005:9005
    environment:
      - HOST=localhost
      - PORT=9005
      - ROOM_COM_PORT=/dev/ttyUSB1
    networks:
      - coopmaster

networks:
  coopmaster:
    name: coopmaster
