name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set Build Number
        id: vars
        run: echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: doc-document-example
          root_file: document.tex


      - name: Rename PDF with Dynamic Name
        run: |
          mv doc-document-example/document.pdf doc-document-example/coopmaster-${BUILD_NUMBER}.pdf
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: coopmaster-${{ env.BUILD_NUMBER }}
          path: doc-document-example/coopmaster-${{ env.BUILD_NUMBER }}.pdf
