name: Convert LaTeX to docx

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TexLive (with LuaLaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-full

      - name: Generate presentation
        working-directory: doc-presentation-example
        run: pdflatex presentation

      - name: Upload presentation
        uses: actions/upload-artifact@v4
        with:
          name: Presentation
          path: doc-presentation-example/presentation.pdf

      - name: Generate document
        working-directory: doc-document-example
        run: pdflatex document.tex

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: Document
          path: doc-document-example/document.pdf
